params:
  preload:
  - pose:
      position: [-0.390, -0.010, 0.200] # meters
      orientation: [180, 0.0, 180]      # degrees
    stop_conditions: {min_force_z: -60.0}
  - {balance: pose}
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, -0.003]
    stop_conditions: {min_force_z: -60.0}
  test:
  - jog:
      angular: [0.0, 0.07, 0.0]
      linear: [0.0, 0.0, 0.001]
    stop_conditions: {max_position_z: 0.02}
type: sequence
