type: 'sequence'
params:
  preload:
    # Step 0: Balance the pose
    - balance: 'pose'

    # Step 1: Preload
    - jog: 
        linear: [0, 0, -0.003] # [mm/sec]
        angular: [0.0, 0, 0]    # [rad/sec]
      stop_conditions:
        min_force_z: -60 # [N]

  test:
    # Step 1: Preload
    - jog:
        linear: [0.00, 0.001, 0.001] # [mm/sec]
        angular: [0.0, 0.0, 0.0]   # [rad/sec]
      stop_conditions:
        max_position_z: 0.02 # [m]