params:
  preload:
  - balance: 'pose'
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, -0.001]
    stop_conditions: {min_force_z: -85.0}
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, 0.0]
    stop_conditions: {max_time: 5.0}
  test:
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, 0.0005]
    stop_conditions: {max_force_x: 20.0, max_force_y: 20.0, max_force_z: 10.0}
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, 0.0]
    stop_conditions: {max_time: 10.0}
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, 0.0005]
    stop_conditions: {max_position_z: 0.05}
type: sequence
