params:
  preload:
  - pose:
      position: [-0.390, -0.010, 0.200] # meters
      orientation: [180, 0.0, 180]      # degrees
    stop_conditions: {min_force_z: -60.0}
  - {balance: pose}
  - {balance: ft}
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, -0.001]
    stop_conditions: {min_force_z: -10.0}
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, 0.0005]
    stop_conditions: {max_force_z: -5.0}
  test:
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [-0.0005, 0.0, 0.0]
    stop_conditions: {min_position_x: -0.06}
type: sequence
