params:
  preload:
  - pose:
      orientation: [180.0, 0.0, 90.0]
      position: [-0.5, 0.05, 0.165]
      time: 5.0
  - {balance: pose}
  - {balance: ft}
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, 0.0]
    stop_conditions: {max_time: 5.0}
  test:
  - jog:
      angular: [0.0, 0.0, 0.0]
      linear: [0.0, 0.0, 0.002]
    stop_conditions: {max_position_z: 0.1}
type: sequence
