color_scheme:
    primary_normal: "#004082"
    primary_active: "#004082"
    primary_disabled: "#dddddd"
    secondary_normal: "#4fa6ff"
    secondary_active: "#4fa6ff"
    secondary_disabled: "#dddddd"
    background: "#ffffff"
    graph:
        primary:
            palette: "hls"
            args: {l: 0.4}

        primary_light:
            palette: "hls"
            args: {l: 0.9}

config_file_types:
    - ["Yaml Files", ".yaml"]
    - ["All Files", ".*"]

data_file_types:
    - ["CSV Files", ".csv"]
    - ["All Files", ".*"]


stop_conditions:
    time: [max]
    force_x: [min, max]
    force_y: [min, max]
    force_z: [min, max]
    torque_x: [min, max]
    torque_y: [min, max]
    torque_z: [min, max]
    position_x: [min, max]
    position_y: [min, max]
    position_z: [min, max]
    orientation_x: [min, max]
    orientation_y: [min, max]
    orientation_z: [min, max]

balance_options: ['pose', 'ft']
    

