color_scheme:
    primary_normal: "#004082"
    primary_active: "#004082"
    primary_disabled: "#dddddd"
    secondary_normal: "#4fa6ff"
    secondary_active: "#4fa6ff"
    secondary_disabled: "#dddddd"
    background: "#ffffff"
    
    stop_conditions:
        default: ['#000000', '#ffffff']
        time: ['#fff0f0', '#cc1800']
        force_x: ['#e6f0ff', '#0024c4']
        force_y: ['#e6f0ff', '#0024c4']
        force_z: ['#e6f0ff', '#0024c4']
        torque_x: ['#ffe6f6', '#ff00a3']
        torque_y: ['#ffe6f6', '#ff00a3']
        torque_z: ['#ffe6f6', '#ff00a3']
        position_x: ['#fffce6', '#ccaa00']
        position_y: ['#fffce6', '#ccaa00']
        position_z: ['#fffce6', '#ccaa00']
        orientation_x: ['#e6fffb', '#00cc22']
        orientation_y: ['#e6fffb', '#00cc22']
        orientation_z: ['#e6fffb', '#00cc22']
    
config_file_types:
    - ["Yaml Files", ".yaml"]
    - ["All Files", ".*"]

data_file_types:
    - ["CSV Files", ".csv"]
    - ["All Files", ".*"]

data_save_loc: '~/Documents/armstron_data'


stop_conditions:
    time: [max]
    force_x: [min, max]
    force_y: [min, max]
    force_z: [min, max]
    torque_x: [min, max]
    torque_y: [min, max]
    torque_z: [min, max]
    position_x: [min, max]
    position_y: [min, max]
    position_z: [min, max]
    orientation_x: [min, max]
    orientation_y: [min, max]
    orientation_z: [min, max]

balance_options: ['pose', 'ft']
    

